In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)

df = pd.read_csv('data/ufc-master.csv')
df.shape

(7177, 118)

In [2]:
df.columns.tolist()

['R_fighter',
 'B_fighter',
 'R_odds',
 'B_odds',
 'R_ev',
 'B_ev',
 'date',
 'location',
 'country',
 'Winner',
 'title_bout',
 'weight_class',
 'gender',
 'no_of_rounds',
 'B_current_lose_streak',
 'B_current_win_streak',
 'B_draw',
 'B_avg_SIG_STR_landed',
 'B_avg_SIG_STR_pct',
 'B_avg_SUB_ATT',
 'B_avg_TD_landed',
 'B_avg_TD_pct',
 'B_longest_win_streak',
 'B_losses',
 'B_total_rounds_fought',
 'B_total_title_bouts',
 'B_win_by_Decision_Majority',
 'B_win_by_Decision_Split',
 'B_win_by_Decision_Unanimous',
 'B_win_by_KO/TKO',
 'B_win_by_Submission',
 'B_win_by_TKO_Doctor_Stoppage',
 'B_wins',
 'B_Stance',
 'B_Height_cms',
 'B_Reach_cms',
 'B_Weight_lbs',
 'R_current_lose_streak',
 'R_current_win_streak',
 'R_draw',
 'R_avg_SIG_STR_landed',
 'R_avg_SIG_STR_pct',
 'R_avg_SUB_ATT',
 'R_avg_TD_landed',
 'R_avg_TD_pct',
 'R_longest_win_streak',
 'R_losses',
 'R_total_rounds_fought',
 'R_total_title_bouts',
 'R_win_by_Decision_Majority',
 'R_win_by_Decision_Split',
 'R_win_by_Decision_Unanimous',
 'R_win_by_KO/TKO',
 'R_win_by_Submission',
 'R_win_by_TKO_Doctor_Stoppage',
 'R_wins',
 'R_Stance',
 'R_Height_cms',
 'R_Reach_cms',
 'R_Weight_lbs',
 'R_age',
 'B_age',
 'lose_streak_dif',
 'win_streak_dif',
 'longest_win_streak_dif',
 'win_dif',
 'loss_dif',
 'total_round_dif',
 'total_title_bout_dif',
 'ko_dif',
 'sub_dif',
 'height_dif',
 'reach_dif',
 'age_dif',
 'sig_str_dif',
 'avg_sub_att_dif',
 'avg_td_dif',
 'empty_arena',
 'B_match_weightclass_rank',
 'R_match_weightclass_rank',
 "R_Women's Flyweight_rank",
 "R_Women's Featherweight_rank",
 "R_Women's Strawweight_rank",
 "R_Women's Bantamweight_rank",
 'R_Heavyweight_rank',
 'R_Light Heavyweight_rank',
 'R_Middleweight_rank',
 'R_Welterweight_rank',
 'R_Lightweight_rank',
 'R_Featherweight_rank',
 'R_Bantamweight_rank',
 'R_Flyweight_rank',
 'R_Pound-for-Pound_rank',
 "B_Women's Flyweight_rank",
 "B_Women's Featherweight_rank",
 "B_Women's Strawweight_rank",
 "B_Women's Bantamweight_rank",
 'B_Heavyweight_rank',
 'B_Light Heavyweight_rank',
 'B_Middleweight_rank',
 'B_Welterweight_rank',
 'B_Lightweight_rank',
 'B_Featherweight_rank',
 'B_Bantamweight_rank',
 'B_Flyweight_rank',
 'B_Pound-for-Pound_rank',
 'better_rank',
 'finish',
 'finish_details',
 'finish_round',
 'finish_round_time',
 'total_fight_time_secs',
 'r_dec_odds',
 'b_dec_odds',
 'r_sub_odds',
 'b_sub_odds',
 'r_ko_odds',
 'b_ko_odds']

In [3]:
df.head()

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,title_bout,weight_class,gender,no_of_rounds,B_current_lose_streak,B_current_win_streak,B_draw,B_avg_SIG_STR_landed,B_avg_SIG_STR_pct,B_avg_SUB_ATT,B_avg_TD_landed,B_avg_TD_pct,B_longest_win_streak,B_losses,B_total_rounds_fought,B_total_title_bouts,B_win_by_Decision_Majority,B_win_by_Decision_Split,B_win_by_Decision_Unanimous,B_win_by_KO/TKO,B_win_by_Submission,B_win_by_TKO_Doctor_Stoppage,B_wins,B_Stance,B_Height_cms,B_Reach_cms,B_Weight_lbs,R_current_lose_streak,R_current_win_streak,R_draw,R_avg_SIG_STR_landed,R_avg_SIG_STR_pct,R_avg_SUB_ATT,R_avg_TD_landed,R_avg_TD_pct,R_longest_win_streak,R_losses,R_total_rounds_fought,R_total_title_bouts,R_win_by_Decision_Majority,R_win_by_Decision_Split,R_win_by_Decision_Unanimous,R_win_by_KO/TKO,R_win_by_Submission,R_win_by_TKO_Doctor_Stoppage,R_wins,R_Stance,R_Height_cms,R_Reach_cms,R_Weight_lbs,R_age,B_age,lose_streak_dif,win_streak_dif,longest_win_streak_dif,win_dif,loss_dif,total_round_dif,total_title_bout_dif,ko_dif,sub_dif,height_dif,reach_dif,age_dif,sig_str_dif,avg_sub_att_dif,avg_td_dif,empty_arena,B_match_weightclass_rank,R_match_weightclass_rank,R_Women's Flyweight_rank,R_Women's Featherweight_rank,R_Women's Strawweight_rank,R_Women's Bantamweight_rank,R_Heavyweight_rank,R_Light Heavyweight_rank,R_Middleweight_rank,R_Welterweight_rank,R_Lightweight_rank,R_Featherweight_rank,R_Bantamweight_rank,R_Flyweight_rank,R_Pound-for-Pound_rank,B_Women's Flyweight_rank,B_Women's Featherweight_rank,B_Women's Strawweight_rank,B_Women's Bantamweight_rank,B_Heavyweight_rank,B_Light Heavyweight_rank,B_Middleweight_rank,B_Welterweight_rank,B_Lightweight_rank,B_Featherweight_rank,B_Bantamweight_rank,B_Flyweight_rank,B_Pound-for-Pound_rank,better_rank,finish,finish_details,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds
0,Israel Adesanya,Joe Pyfer,-130.0,102.0,76.9231,102.0000,2026-03-28,"Seattle, Washington, USA",USA,Blue,False,Middleweight,MALE,5,0,3,0,3.52,0.44,0.9,1.45,0.30,4,2,18,0,0,0,1,4,2,0,7,Orthodox,187.96,190.50,185,3,0,0,4.03,0.48,0.1,0.05,0.09,9,5,66,12,0,1,7,5,0,0,13,Switch,193.04,203.20,185,36,29,-3,3,-5,-6,-3,-48,-12,-1,2,-5.08,-12.70,-7,-0.51,0.8,1.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KO/TKO,Punches,2.0,4:18,558.0,163.0,900.0,2500.0,400.0,300.0,250.0
1,Alexa Grasso,Maycee Barber,124.0,-158.0,124.0000,63.2911,2026-03-28,"Seattle, Washington, USA",USA,Red,False,Women's Flyweight,FEMALE,3,0,7,0,4.56,0.53,0.1,1.56,0.45,7,2,34,0,0,2,4,5,0,0,11,Switch,165.10,165.10,125,2,0,1,4.11,0.41,0.7,0.40,0.35,5,5,45,3,0,1,5,0,2,0,8,Orthodox,165.10,167.64,125,32,27,-2,7,2,3,-3,-11,-3,5,-2,0.00,-2.54,-5,0.45,-0.6,1.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KO/TKO,Punch,1.0,2:42,162.0,175.0,105.0,1400.0,800.0,2500.0,500.0
2,Michael Chiesa,Niko Price,-901.0,550.0,11.0988,550.0000,2026-03-28,"Seattle, Washington, USA",USA,Red,False,Welterweight,MALE,3,3,0,0,5.11,0.43,0.6,1.06,0.30,2,10,40,0,0,0,2,4,2,0,8,Orthodox,182.88,193.04,170,0,3,0,2.02,0.40,1.0,3.11,0.47,4,7,47,1,0,0,6,0,8,0,14,Southpaw,185.42,190.50,170,38,36,3,-3,-2,-6,3,-7,-1,4,-6,-2.54,2.54,-2,3.09,-0.4,-2.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SUB,Rear Naked Choke,1.0,1:03,63.0,225.0,900.0,-150.0,1600.0,600.0,1000.0
3,Julian Erosa,Lerryan Douglas,235.0,-320.0,235.0000,31.2500,2026-03-28,"Seattle, Washington, USA",USA,Blue,False,Featherweight,MALE,3,0,1,0,8.67,0.64,0.0,0.00,0.00,1,0,1,0,0,0,0,1,0,0,1,Orthodox,175.26,182.88,145,1,0,0,6.18,0.48,0.7,1.73,0.43,3,8,36,0,0,2,1,3,4,0,10,Southpaw,185.42,187.96,145,36,30,-1,1,-2,-9,-8,-35,0,-2,-4,-10.16,-5.08,-6,2.49,-0.7,-1.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KO/TKO,Punches,1.0,3:33,213.0,600.0,500.0,600.0,2000.0,700.0,-150.0
4,Mansur Abdul-Malik,Yousri Belgaroui,-158.0,124.0,63.2911,124.0000,2026-03-28,"Seattle, Washington, USA",USA,Blue,False,Middleweight,MALE,3,0,2,0,6.10,0.64,0.0,0.29,1.00,2,1,9,0,0,0,0,2,0,0,2,Orthodox,198.12,200.66,185,0,4,1,3.28,0.44,0.3,1.65,0.41,3,0,9,0,0,0,0,3,1,0,4,Orthodox,187.96,203.20,185,28,33,0,-2,-1,-2,1,0,0,-1,-1,10.16,-2.54,5,2.82,-0.3,-1.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KO/TKO,Knee,3.0,3:39,819.0,350.0,240.0,800.0,1800.0,240.0,250.0

In [4]:
df.dtypes

R_fighter         str
B_fighter         str
R_odds        float64
B_odds        float64
R_ev          float64
               ...
b_dec_odds    float64
r_sub_odds    float64
b_sub_odds    float64
r_ko_odds     float64
b_ko_odds     float64
Length: 118, dtype: object

In [5]:
[c for c in df.columns if not c.startswith(('R_', 'B_', 'r_', 'b_'))]

['date',
 'location',
 'country',
 'Winner',
 'title_bout',
 'weight_class',
 'gender',
 'no_of_rounds',
 'lose_streak_dif',
 'win_streak_dif',
 'longest_win_streak_dif',
 'win_dif',
 'loss_dif',
 'total_round_dif',
 'total_title_bout_dif',
 'ko_dif',
 'sub_dif',
 'height_dif',
 'reach_dif',
 'age_dif',
 'sig_str_dif',
 'avg_sub_att_dif',
 'avg_td_dif',
 'empty_arena',
 'better_rank',
 'finish',
 'finish_details',
 'finish_round',
 'finish_round_time',
 'total_fight_time_secs']

In [6]:
[c for c in df.columns if c.startswith('R_')]

['R_fighter',
 'R_odds',
 'R_ev',
 'R_current_lose_streak',
 'R_current_win_streak',
 'R_draw',
 'R_avg_SIG_STR_landed',
 'R_avg_SIG_STR_pct',
 'R_avg_SUB_ATT',
 'R_avg_TD_landed',
 'R_avg_TD_pct',
 'R_longest_win_streak',
 'R_losses',
 'R_total_rounds_fought',
 'R_total_title_bouts',
 'R_win_by_Decision_Majority',
 'R_win_by_Decision_Split',
 'R_win_by_Decision_Unanimous',
 'R_win_by_KO/TKO',
 'R_win_by_Submission',
 'R_win_by_TKO_Doctor_Stoppage',
 'R_wins',
 'R_Stance',
 'R_Height_cms',
 'R_Reach_cms',
 'R_Weight_lbs',
 'R_age',
 'R_match_weightclass_rank',
 "R_Women's Flyweight_rank",
 "R_Women's Featherweight_rank",
 "R_Women's Strawweight_rank",
 "R_Women's Bantamweight_rank",
 'R_Heavyweight_rank',
 'R_Light Heavyweight_rank',
 'R_Middleweight_rank',
 'R_Welterweight_rank',
 'R_Lightweight_rank',
 'R_Featherweight_rank',
 'R_Bantamweight_rank',
 'R_Flyweight_rank',
 'R_Pound-for-Pound_rank']

In [7]:
df[df['R_fighter'] == 'Jim Miller'].sort_values('date')[['date', 'R_wins', 'R_total_rounds_fought']]

            date  R_wins  R_total_rounds_fought
7160  2010-03-27       5                     15
7042  2010-09-15       6                     18
6969  2010-12-11       7                     21
6904  2011-03-19       8                     22
6802  2011-08-14       9                     25
6340  2012-12-29      10                     31
5966  2013-12-28      11                     37
5817  2014-04-26      12                     38
5342  2015-04-18      13                     41
5184  2015-07-25      13                     44
5040  2015-12-10      14                     47
4784  2016-07-09      14                     52
4625  2016-11-12      16                     56
3950  2018-04-21      17                     68
3780  2018-09-08      17                     69
3626  2018-12-15      18                     70
3460  2019-04-27      18                     71
3307  2019-08-03      19                     73
3064  2020-02-15      20                     73
2936  2020-06-20      20                     76
2845  2020-08-15      21                     77
2527  2021-04-10      21                     80
2264  2021-10-16      21                     83
2102  2022-02-19      22                     85
1897  2022-07-02      23                     87
1598  2023-02-18      24                     89
1440  2023-06-03      24                     92
1139  2024-01-13      25                     93
682   2024-11-16      26                     99
486   2025-04-12      27                    100

In [8]:
print(df['finish'].value_counts())
print(df['Winner'].value_counts())

finish
U-DEC         2681
KO/TKO        2223
SUB           1260
S-DEC          699
M-DEC           52
DQ              18
CNC              3
Overturned       3
Name: count, dtype: int64
Winner
Red           4145
Blue          3024
Draw             5
No Contest       3
Name: count, dtype: int64

In [9]:
df['date'] = pd.to_datetime(df['date'])
df['date'].dtype

dtype('<M8[us]')

In [10]:
df[df['finish'].isnull()]['date'].describe()

count                           238
mean     2016-09-03 00:24:12.100840
min             2010-05-29 00:00:00
25%             2014-08-28 06:00:00
50%             2016-08-16 12:00:00
75%             2019-02-23 00:00:00
max             2020-09-12 00:00:00
Name: date, dtype: object

In [11]:
df_clean = df[df['Winner'].isin(['Red', 'Blue'])]
df_clean = df_clean[df_clean['finish'].notnull()]
df_clean.shape

(6931, 118)

In [12]:
finish_map = {
    'U-DEC': 'DEC',
    'S-DEC': 'DEC',
    'SUB': 'SUB',
    'KO/TKO': 'KO/TKO',
    'M-DEC': 'DEC',
    # ... you fill in the rest
}
df_clean['method'] = df_clean['finish'].map(finish_map)
df_clean['method'].value_counts(dropna=False)

/var/folders/hs/dqvp5vy92s97mm41fgb1m8100000gn/T/ipykernel_53627/2270014592.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_clean['method'] = df_clean['finish'].map(finish_map)

method
DEC       3428
KO/TKO    2223
SUB       1260
NaN         20
Name: count, dtype: int64

In [13]:
df_clean = df_clean[df_clean['method'].notnull()].copy()
df_clean.shape

(6911, 119)

In [16]:
(df_clean['method'].value_counts(normalize=True)* 100).round(1)

method
DEC       49.6
KO/TKO    32.2
SUB       18.2
Name: proportion, dtype: float64

In [17]:
(df_clean['Winner'].value_counts(normalize=True)* 100).round(1)

Winner
Red     57.7
Blue    42.3
Name: proportion, dtype: float64

In [19]:
(df_clean.groupby('method')['Winner'].value_counts(normalize=True)* 100).round(1)

method  Winner
DEC     Red       57.6
        Blue      42.4
KO/TKO  Red       55.9
        Blue      44.1
SUB     Red       61.5
        Blue      38.5
Name: proportion, dtype: float64